### PR TITLE
 Change Readme.txt to README.md

### PR DESCRIPTION
**Pull request by deran2016**
Improved readability using markdown language.

### CODE REVIEW

**Comment by jubin-park** [comment]
Hello, @deran2016.
Thank you for your commits.

**Comment by deran2016** [comment]
Thank you.

**Comment by jubin-park** [comment]
Hi, @deran2016 !
I'm sorry that your README.md was deleted because of original document copyright issue.
It's my fault. From now README deals with RGDirectXP document ONLY. Sorry.

**Comment by deran2016** [comment]
Hi, @jubin-park !
It’s okay!
Thanks to tell me why my README.md was deleted.
I think copyright issue is very important, too.

**Pull request merged**
